database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: excellence

  # the password
  password: excellence

  # the JDBC URL
  url: jdbc:postgresql://db:5432/excellence

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: true

  # this should help to detect closed connections
  checkConnectionOnBorrow: true

logging:
  level: INFO
  loggers:
    "io.dropwizard": DEBUG
    "org.hibernate.engine":
      level: WARNING
      additive: false
  appenders:
    - type: console
      threshold: DEBUG

server:
  gzip:
    syncFlush: true
