version: '3.8'

services:
  server:
    # TODO: image: "<url>/<1>/<2>:latest"
    build: ./
    depends_on:
      - "db"
    restart: always
    container_name: "excellence-backend"
    networks:
      - excellence
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - $PWD/containerdata/excellence-backend:/data
  db:
    image: postgres:12-alpine
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - excellence
    environment:
      POSTGRES_USER: excellence
      POSTGRES_PASSWORD: excellence
    volumes:
      - $PWD/containerdata/postgresql:/var/lib/postgresql/data

networks:
  excellence:
    driver: bridge
    name: excellence
